markdown: redcarpet
baseurl: /jekyll-learn
exclude: ['README.md']
port: 8123

# permalink: pretty
# gems: ['jekyll-multiple-languages']
# languages: ['en','cn']
# language_default: 'en'
# fill_default_content: true